// Central SEO source of truth for the Americell marketing site.
//
// Everything metadata-related derives from this module so titles, canonical
// URLs, Open Graph, Twitter cards, and robots directives stay consistent
// across every route. Route segments import `buildMetadata` and pass only
// the overrides they care about.
//
// Next.js 16 App Router: `Metadata` / `Viewport` are consumed via the
// `metadata` / `viewport` exports of layouts and pages. The Open Graph image
// is generated by the file-based `app/opengraph-image` route (next/og
// `ImageResponse`), so the `images` entry references that path.

import type { Metadata, Viewport } from "next";

/**
 * Canonical origin for the site. Absolute URLs (canonical, OG, Twitter) are
 * resolved against this via `metadataBase`. Override in production by setting
 * `NEXT_PUBLIC_SITE_URL` (no trailing slash).
 */
export const SITE_URL: string =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://americell.example";

/** Human-readable site / brand name. */
export const SITE_NAME = "Americell" as const;

/** Default page title used when a route does not supply its own. */
export const DEFAULT_TITLE =
  "Americell — Αληθινά τηλέφωνα ΗΠΑ που ελέγχεις από οπουδήποτε" as const;

/**
 * Rich, benefit-led default description. Kept near ~155 characters so it is
 * unlikely to be truncated in search-result snippets.
 */
export const DEFAULT_DESCRIPTION =
  "Η Americell σού δίνει αληθινά, φυσικά smartphone ΗΠΑ σε datacenter ΗΠΑ — έλεγξέ τα ζωντανά στον browser σου, αυτοματοποίησε επαναλαμβανόμενες ροές και διαχειρίσου έναν ολόκληρο στόλο από ένα dashboard. Χωρίς emulators, χωρίς καλώδια.";

/** Topical keyword set surfaced in metadata. */
export const KEYWORDS: string[] = [
  "cloud τηλέφωνο",
  "απομακρυσμένο τηλέφωνο",
  "αληθινό τηλέφωνο ΗΠΑ",
  "smartphone ΗΠΑ στο cloud",
  "τηλεχειρισμός συσκευών",
  "φάρμα κινητών συσκευών",
  "δοκιμές σε αληθινές συσκευές",
  "QA εφαρμογών κινητού",
  "απομακρυσμένο Android",
  "απομακρυσμένο iPhone",
  "αυτοματισμός συσκευών",
  "φιλοξενούμενα smartphone",
  "οικιακές κινητές συσκευές",
  "Americell",
];

/** Absolute URL to the generated Open Graph / Twitter card image route. */
export const OG_IMAGE_PATH = "/opengraph-image" as const;

/**
 * A subset of `Metadata` that callers may override. `title` accepts the same
 * shape Next.js allows (string or a title template descriptor).
 */
export type MetadataOverrides = Omit<Metadata, "title"> & {
  title?: Metadata["title"];
};

/**
 * Build a fully-formed Next.js `Metadata` object from optional per-route
 * overrides. The returned object is safe to export directly as `metadata`
 * (static) or from `generateMetadata`.
 *
 * Overrides are shallow-merged over the defaults, with `openGraph`, `twitter`,
 * `robots`, and `alternates` deep-merged so a caller can tweak a single field
 * (e.g. a canonical path) without discarding the rest.
 */
export function buildMetadata(overrides: MetadataOverrides = {}): Metadata {
  const {
    title,
    description = DEFAULT_DESCRIPTION,
    openGraph,
    twitter,
    robots,
    alternates,
    keywords,
    ...rest
  } = overrides;

  const resolvedTitle: Metadata["title"] = title ?? {
    default: DEFAULT_TITLE,
    template: `%s · ${SITE_NAME}`,
  };

  // Deep-merge object-valued overrides; if a caller passes a string/null (both
  // valid per the Metadata types), replace the field wholesale instead.
  const isObject = (value: unknown): value is Record<string, unknown> =>
    typeof value === "object" && value !== null;

  const resolvedAlternates: Metadata["alternates"] = isObject(alternates)
    ? { canonical: "/", ...alternates }
    : (alternates ?? { canonical: "/" });

  const resolvedOpenGraph: Metadata["openGraph"] = {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
    images: [OG_IMAGE_PATH],
    locale: "el_GR",
    ...(isObject(openGraph) ? openGraph : {}),
  };

  const resolvedTwitter: Metadata["twitter"] = {
    card: "summary_large_image",
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
    images: [OG_IMAGE_PATH],
    ...(isObject(twitter) ? twitter : {}),
  };

  const resolvedRobots: Metadata["robots"] =
    typeof robots === "string"
      ? robots
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-image-preview": "large",
            "max-snippet": -1,
            "max-video-preview": -1,
          },
          ...(isObject(robots) ? robots : {}),
        };

  return {
    metadataBase: new URL(SITE_URL),
    title: resolvedTitle,
    description,
    applicationName: SITE_NAME,
    category: "technology",
    keywords: keywords ?? KEYWORDS,
    alternates: resolvedAlternates,
    openGraph: resolvedOpenGraph,
    twitter: resolvedTwitter,
    robots: resolvedRobots,
    ...rest,
  };
}

/**
 * Root `viewport` export. Kept separate from `metadata` per the Next.js 16
 * split of viewport/theme-color out of the metadata object.
 */
export const VIEWPORT: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
  colorScheme: "light dark",
};
